# Generated by Django 2.2.5 on 2019-12-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(auto_now=True)),
                ('modification', models.CharField(default='B', max_length=1)),
                ('photo', models.ImageField(default='/static/images/upload.png', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfilePhoto',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='N', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, default='2019-12-10')),
                ('religion', models.CharField(default='N/A', max_length=25)),
                ('caste', models.CharField(default='N/A', max_length=25)),
                ('sub_caste', models.CharField(default='N/A', max_length=25)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='N/A', max_length=50)),
                ('address', models.TextField(default=' ', max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('marital_status', models.CharField(default='N', max_length=1)),
                ('education', models.CharField(default='N', max_length=1)),
                ('specialization', models.CharField(default='N/A', max_length=100)),
                ('body_type', models.CharField(default='N', max_length=1)),
                ('differently_able', models.CharField(default='N', max_length=1)),
                ('drinks', models.CharField(default='N', max_length=1)),
                ('smoke', models.CharField(default='N', max_length=1)),
                ('mother_tongue', models.CharField(default='N/A', max_length=50)),
                ('blood_group', models.CharField(default='N', max_length=3)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('skin_color', models.CharField(default='6', max_length=1)),
                ('diet', models.CharField(default='N', max_length=1)),
                ('occupation', models.CharField(default='N/A', max_length=200)),
                ('annual_income', models.IntegerField(default=0)),
                ('fathers_occupation', models.CharField(default='N/A', max_length=200)),
                ('mothers_occupation', models.CharField(default='N/A', max_length=200)),
                ('no_sisters', models.IntegerField(default=0)),
                ('no_brothers', models.IntegerField(default=0)),
                ('about_me', models.TextField(default='N/A', max_length=500)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_profile.ProfilePhoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
