# Generated by Django 2.2.5 on 2019-12-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('interested_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='my_profile.UserProfile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.UserProfile')),
            ],
            options={
                'db_table': 'InterestedProfile',
            },
        ),
    ]
