# Generated by Django 2.2.5 on 2019-12-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Married',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_date', models.DateField(default='2019-05-05')),
                ('marriage_date', models.DateField(default='2019-05-05')),
                ('photo', models.ImageField(default='/static/images/upload.png', upload_to='our_marriage_photo/')),
                ('he', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.UserProfile')),
                ('she', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='married_she', to='my_profile.UserProfile')),
            ],
        ),
    ]
