# Generated by Django 2.2.5 on 2019-12-25 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_profile', '0005_auto_20191225_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(default=0)),
                ('age_to', models.IntegerField(default=100)),
                ('religion', models.CharField(default='N/A', max_length=25)),
                ('caste', models.CharField(default='N/A', max_length=25)),
                ('sub_caste', models.CharField(default='N/A', max_length=25)),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(default='N/A', max_length=50)),
                ('marital_status', models.CharField(default='N', max_length=1)),
                ('education', models.CharField(default='N', max_length=1)),
                ('specialization', models.CharField(default='N/A', max_length=100)),
                ('body_type', models.CharField(default='N', max_length=1)),
                ('mother_tongue', models.CharField(default='N/A', max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('skin_color', models.CharField(default='6', max_length=1)),
                ('diet', models.CharField(default='N', max_length=1)),
                ('occupation', models.CharField(default='N/A', max_length=200)),
                ('about_my_partner', models.TextField(default='N/A', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProfilePreference',
            },
        ),
    ]
